# Generated by Django 3.0 on 2019-12-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date_published')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(verbose_name='date_completed')),
            ],
        ),
    ]
