# Generated by Django 3.0 on 2019-12-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
