# Generated by Django 3.0 on 2019-12-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoItem', '0003_auto_20191216_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='task_text',
            field=models.TextField(max_length=200),
        ),
    ]
