# Generated by Django 3.0.1 on 2019-12-23 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 12, 23, 20, 32, 22, 181690, tzinfo=utc))),
            ],
        ),
    ]
