# Generated by Django 3.0.1 on 2019-12-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
